from os import path
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.mainIndex, name='mainIndex'),
    re_path('mainIndex', views.mainIndex, name='mainIndex'),
    re_path('register', views.register, name='register'),
    re_path('createReg', views.createReg, name='createReg'),
    re_path('index', views.index, name='index'),
    re_path('booking', views.booking, name='search'),
    re_path('DBLogin', views.DBLogin, name='DBLogin'),  
    re_path('Admin',views.Admin,name='admin'),
    re_path('ADLogin',views.ADLogin,name='ADLogin'),
    re_path('adminIndex',views.adminIndex,name='adminIndex'),
    re_path('addCenter',views.addCenter,name='addCenter'),
    re_path('CDLogin',views.CDLogin,name='CDLogin'),
    re_path('centerhome',views.centerhome,name='centerhome'),
    re_path('booked',views.booked,name='booked'),
    re_path('vcb',views.vcb,name='vcb'),
    re_path('view_reports',views.view_reports,name='view_reports'),
    re_path('filterDate', views.filterDate, name='filterDate'),
    re_path('centerProfile',views.centerProfile,name='centerProfile'),
    re_path('stock',views.stock,name='stock'),
    re_path('centerselect',views.centerselect,name='centerselect'),
    re_path('filterCenter',views.filterCenter,name='filterCenter'),
    re_path('editvc', views.editvc, name='editvc'),  
    re_path('updatevc', views.updatevc, name='updatevc'),
    re_path('vchistory',views.vchistory,name='vchistory'),
    re_path('approved',views.approved,name='approved'),
    re_path('updatingvc',views.updatingvc,name='updatingvc'),
    re_path('details',views.details,name='details'),
    re_path('view_certificate',views.view_certificate,name='view_certificate'),
    re_path('workBench',views.workBench,name='workBench'),
    re_path("update-status/", views.update_status, name="update_status"),
    re_path(r'password-reset/verify/(?P<email>[^/]+)/', views.password_reset_verify, name='password_reset_verify'),
    re_path('password_reset/', views.password_reset_request, name='password_reset_request'),
    re_path('userprofile',views.userprofile,name='userprofile'),
    re_path('userfeedback',views.userfeedback,name='userfeedback'),
    re_path('centerfeedback',views.centerfeedback,name='centerfeedback'),
    re_path('admindash',views.admindash,name='admindash'),
    re_path('api/dashboard-data/', views.dashboard_data, name='dashboard-data'),
    re_path('manageuser',views.manageuser,name='manageuser'),
    re_path('manage_centers/', views.manage_centers, name='manage_centers'),
    re_path('vaccinated_users/', views.vaccinated_users, name='vaccinated_users'),
    re_path('manage_center/', views.manage_center, name='manage_center'),
    re_path('add_center/', views.add_center, name='add_center'),
    re_path('manage_feedback/', views.manage_feedback, name='manage_feedback'),
            
]