# Generated by Django 5.1.4 on 2024-12-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
                ('Mobile', models.CharField(max_length=20)),
                ('Dob', models.CharField(max_length=10)),
            ],
        ),
    ]
