# Generated by Django 5.1.4 on 2024-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='centerReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.CharField(max_length=100)),
                ('Cname', models.CharField(max_length=100)),
                ('Cplace', models.CharField(max_length=100)),
            ],
        ),
    ]
