# Generated by Django 5.1.4 on 2024-12-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_centerreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='vcbk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=100)),
                ('cdate', models.CharField(max_length=10)),
            ],
        ),
    ]
