# Generated by Django 5.1.4 on 2024-12-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_vcbk'),
    ]

    operations = [
        migrations.CreateModel(
            name='vccinUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CenterID', models.CharField(max_length=50)),
                ('CN', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=10)),
                ('DTP', models.CharField(max_length=50)),
                ('HepatitisB', models.CharField(max_length=50)),
                ('Polio', models.CharField(max_length=50)),
                ('Hib', models.CharField(max_length=50)),
                ('Rotavirus', models.CharField(max_length=50)),
                ('PCV', models.CharField(max_length=50)),
                ('Influenza', models.CharField(max_length=50)),
                ('MMR', models.CharField(max_length=50)),
                ('VitaminA', models.CharField(max_length=50)),
                ('Varicella', models.CharField(max_length=50)),
                ('HepatitisA', models.CharField(max_length=50)),
                ('TT', models.CharField(max_length=50)),
                ('HPV', models.CharField(max_length=50)),
            ],
        ),
    ]
