# Generated by Django 5.1.4 on 2024-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_vccinupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REmail', models.CharField(max_length=50)),
                ('CHName', models.CharField(max_length=50)),
                ('VCD', models.CharField(max_length=50)),
                ('DT', models.CharField(max_length=50)),
                ('UVCN', models.CharField(max_length=50)),
                ('UVD', models.CharField(max_length=50)),
            ],
        ),
    ]
