# Generated by Django 5.1.4 on 2025-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='boo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=50)),
                ('childname', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=100)),
                ('cdate', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='vcbk',
        ),
    ]
