# Generated by Django 5.1.4 on 2025-01-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_boo_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boo',
            new_name='bok',
        ),
    ]
