# Generated by Django 5.1.4 on 2025-01-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_user_otp_user_otp_created_at_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
    ]
