# Generated by Django 5.1.4 on 2025-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_rename_email_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ufeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUN', models.CharField(max_length=50)),
                ('Feed', models.CharField(max_length=100)),
            ],
        ),
    ]
