# Generated by Django 5.1.4 on 2025-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_ufeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCN', models.CharField(max_length=50)),
                ('CFeed', models.CharField(max_length=100)),
            ],
        ),
    ]
